# gitops-repo/apps/podinfo/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
---
# gitops-repo/apps/podinfo/helmrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  url: https://stefanprodan.github.io/podinfo
---
# gitops-repo/apps/podinfo/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.3.5"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: podinfo.talos-aws-official-nlb-645e4b1f6437f468.elb.eu-west-1.amazonaws.com
          paths:
            - path: /
              pathType: ImplementationSpecific
